package org.oscm.app.ui.appconfiguration;

import java.util.Objects;

/**
 * This is a wrapper for canPing-related error messages, which are generated by each controller's canPing implementation.
 */
public class CanPingErrorWrapper {

    private String errorMessage;
    private String stackTrace;

    /**
     * @param errorMessage Final, formatted, localized error message
     * @param stackTrace   stacktrace of an error
     */
    public CanPingErrorWrapper(String errorMessage, String stackTrace) {
        this.errorMessage = errorMessage;
        this.stackTrace = stackTrace;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public String getStackTrace() {
        return stackTrace;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CanPingErrorWrapper that = (CanPingErrorWrapper) o;
        return errorMessage.equals(that.errorMessage) &&
                stackTrace.equals(that.stackTrace);
    }

    @Override
    public int hashCode() {
        return Objects.hash(errorMessage, stackTrace);
    }
}
